SELECT
    a.ITEM_ID,
    a.ITEM_NAME,
    a.RARITY
FROM
    ITEM_INFO a
WHERE
    a.ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY
    a.ITEM_ID DESC;
